'use client';
import {useEffect,useState} from 'react';
export default function ResetPassword(){
 const [token,setToken]=useState(''),[en,setEn]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const t=(hu:string,english:string)=>en?english:hu;
 useEffect(()=>{setToken(new URLSearchParams(window.location.hash.slice(1)).get('token')||'');history.replaceState(null,'','/admin/reset');setEn(localStorage.getItem('ivett-language')==='en')},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setError('');if(f.get('password')!==f.get('confirm')){setError('match');return}setBusy(true);try{const response=await fetch('/api/auth/recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reset',token,password:f.get('password')})});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error||'unavailable');return}setDone(true);setToken('')}catch{setError('unavailable')}finally{setBusy(false)}}
 return <main className="admin-login"><div className="login-card"><button className="language" onClick={()=>setEn(!en)}>HU / EN</button><h1>{t('Új jelszó','New password')}</h1>{done?<><p role="status">{t('A jelszavad megváltozott. Jelentkezz be az új jelszóval.','Your password has been changed. Sign in with your new password.')}</p><a className="button" href="/admin">{t('Bejelentkezés','Sign in')}</a></>:!token?<p>{t('A visszaállítási link hiányzik. Kérj új linket a bejelentkezési oldalon.','The reset link is missing. Request a new link from the login page.')}</p>:<form className="booking-form" onSubmit={submit}><p>{t('Válassz legalább 12 karakteres jelszót.','Choose a password with at least 12 characters.')}</p><label>{t('Új jelszó','New password')}<input required type="password" name="password" autoComplete="new-password" minLength={12} maxLength={128}/></label><label>{t('Jelszó ismét','Confirm password')}<input required type="password" name="confirm" autoComplete="new-password" minLength={12} maxLength={128}/></label><button className="button" disabled={busy}>{busy?t('Mentés…','Saving…'):t('Jelszó mentése','Save password')}</button>{error&&<p role="alert" className="error">{error==='match'?t('A két jelszó nem egyezik.','Passwords do not match.'):error==='invalid_token'?t('A link lejárt vagy már felhasználtad. Kérj új linket.','This link has expired or has already been used. Request a new link.'):error==='password_length'?t('A jelszó 12–128 karakter hosszú legyen.','Use a password of 12–128 characters.'):t('Nem sikerült menteni. Próbáld újra.','Unable to save. Please try again.')}</p>}</form>}<a href="/admin">← {t('Vissza a bejelentkezéshez','Back to sign in')}</a></div></main>;
}
