'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {calendarDays,calendarMove,timeLabel,type CalendarView} from '@/lib/calendar';
import type {Block} from '@/lib/schedule';
import type {Booking} from './reservations';
export default function BookingCalendar({en,bookings,blocks}:{en:boolean,bookings:Booking[],blocks:Block[]}){
 const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest'}).format(new Date());
 const [date,setDate]=useState(today),[view,setView]=useState<CalendarView>('workweek'),[selected,setSelected]=useState<Booking|null>(null);
 const t=(hu:string,english:string)=>en?english:hu,days=calendarDays(date,view);
 const format=(date:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat(en?'en-GB':'hu-HU',{...options,timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
 const statuses:Record<string,string>={pending:t('Visszaigazolásra vár','Awaiting confirmation'),confirmed:t('Visszaigazolva','Confirmed'),completed:t('Befejezett','Completed'),cancelled:t('Lemondva','Cancelled'),rejected:t('Elutasítva','Rejected')};
 const visible=bookings.filter(b=>days.includes(b.date));
 const from=Math.floor(Math.min(480,...visible.map(b=>b.start))/60)*60,to=Math.ceil(Math.max(1140,...visible.map(b=>b.end))/60)*60,height=to-from;
 const label=(b:Booking)=>`${timeLabel(b.start)}–${timeLabel(b.end)} · ${b.name} · ${b.service_name||b.service} · ${statuses[b.status]}`;
 function dayBookings(day:string){const rows=bookings.filter(b=>b.date===day).sort((a,b)=>a.start-b.start||a.end-b.end);const ends:number[]=[];return {items:rows.map(b=>{let lane=ends.findIndex(end=>end<=b.start);if(lane<0)lane=ends.length;ends[lane]=b.end;return {b,lane}}),get lanes(){return Math.max(1,ends.length)}}}
 return <div className="booking-calendar"><div className="calendar-toolbar"><div><button type="button" aria-label={t('Előző időszak','Previous period')} onClick={()=>setDate(calendarMove(date,view,-1))}>←</button><button type="button" onClick={()=>setDate(today())}>{t('Ma','Today')}</button><button type="button" aria-label={t('Következő időszak','Next period')} onClick={()=>setDate(calendarMove(date,view,1))}>→</button><label>{t('Dátum','Date')}<input type="date" value={date} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value))setDate(e.target.value)}}/></label></div><div role="group" aria-label={t('Naptárnézet','Calendar view')}>{[['day','Nap','Day'],['workweek','Munkahét','Work week'],['week','Teljes hét','Full week'],['month','Hónap','Month']].map(([id,hu,english])=><button type="button" key={id} aria-pressed={view===id} className={view===id?'selected':''} onClick={()=>setView(id as CalendarView)}>{t(hu,english)}</button>)}</div></div>
 <h3>{view==='month'?format(date,{year:'numeric',month:'long'}):days.map(d=>format(d,{month:'short',day:'numeric'})).filter((_,i)=>i===0||i===days.length-1).join(' – ')}</h3><p className="calendar-legend">{Object.entries(statuses).map(([status,name])=><span key={status} className={'calendar-status '+status}>{name}</span>)}<span className="calendar-status blocked">{t('Nem elérhető','Unavailable')}</span></p>
 <div className="calendar-scroll">{view==='month'?<div className="calendar-month">{days.slice(0,7).map(day=><div className="calendar-weekday" key={day}>{format(day,{weekday:'short'})}</div>)}{days.map(day=><div key={day} className={'calendar-day '+(day.slice(0,7)!==date.slice(0,7)?'outside':'')}><button className={day===today()?'calendar-today':''} onClick={()=>{setDate(day);setView('day')}} aria-label={format(day,{dateStyle:'full'})}>{Number(day.slice(-2))}</button>{blocks.filter(b=>b.date_from<=day&&b.date_to>=day).map(b=><span className="calendar-month-block" key={b.id}>{t('Nem elérhető','Unavailable')}{(b.start!==0||b.end!==1440)&&' '+timeLabel(b.start)+'–'+timeLabel(b.end)}</span>)}{dayBookings(day).items.map(({b})=><button key={b.id} className={'calendar-event '+b.status} title={label(b)} onClick={()=>setSelected(b)}>{timeLabel(b.start)}–{timeLabel(b.end)}<br/>{b.name}<br/>{b.service_name||b.service}</button>)}</div>)}</div>:<div className="calendar-time-grid" style={{gridTemplateColumns:`55px repeat(${days.length},minmax(125px,1fr))`}}><div/>{days.map(day=><div className={'calendar-weekday '+(day===today()?'calendar-today':'')} key={day}>{format(day,{weekday:'short',day:'numeric',month:'short'})}</div>)}<div className="calendar-time-labels" style={{height}}>{Array.from({length:(to-from)/60},(_,i)=><span key={i} style={{top:i*60}}>{timeLabel(from+i*60)}</span>)}</div>{days.map(day=>{const layout=dayBookings(day);return <div key={day} className="calendar-time-day" style={{height}}>{blocks.filter(b=>b.date_from<=day&&b.date_to>=day&&b.start<to&&b.end>from).map(b=><div className="calendar-time-block" key={b.id} style={{top:Math.max(b.start,from)-from,height:Math.min(b.end,to)-Math.max(b.start,from)}}>{t('Nem elérhető','Unavailable')}</div>)}{layout.items.map(({b,lane})=><button key={b.id} title={label(b)} className={'calendar-event '+b.status} style={{top:b.start-from,height:Math.max(24,b.end-b.start),left:`${lane*100/layout.lanes}%`,width:`${100/layout.lanes}%`}} onClick={()=>setSelected(b)}><strong>{timeLabel(b.start)}–{timeLabel(b.end)}</strong><br/>{b.name}<br/>{b.service_name||b.service}<br/>{statuses[b.status]}</button>)}</div>})}</div>}</div>
 {!visible.length&&<p>{t('Ebben az időszakban nincs a szűrésnek megfelelő foglalás.','No bookings match this filter in this period.')}</p>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent>{selected&&<><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.date} · {timeLabel(selected.start)}–{timeLabel(selected.end)} · Europe/Budapest</DialogDescription><p>{selected.service_name||selected.service} · {statuses[selected.status]}</p><a href={'mailto:'+selected.email}>{selected.email}</a><a href={'tel:'+selected.phone}>{selected.phone}</a><p>{selected.previous_details}</p></>}</DialogContent></Dialog>
 </div>;
}
