'use client';
import {useState} from 'react';
import {useCatalog} from '@/hooks/use-catalog';
import {type Service} from '@/lib/catalog';
import {money} from '@/lib/services';
import TranslationNote from './translation-note';
export default function CatalogEditor({en}:{en:boolean}){const {services,ready,error,refresh}=useCatalog();const [busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[saved,setSaved]=useState(false);const t=(a:string,b:string)=>en?b:a;
async function save(e:React.FormEvent<HTMLFormElement>,s?:Service){e.preventDefault();setBusy(true);setFailed(false);setSaved(false);const form=e.currentTarget,f=new FormData(form);try{const r=await fetch('/api/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'service',id:s?.id||crypto.randomUUID(),hu:f.get('hu'),en:f.get('en'),descriptionHu:f.get('descriptionHu'),descriptionEn:f.get('descriptionEn'),price:Number(f.get('price')),minutes:Number(f.get('minutes')),active:f.get('active')==='on'?1:0,position:Number(f.get('position'))})});if(!r.ok)throw Error();if(!s)form.reset();await refresh();setSaved(true)}catch{setFailed(true)}finally{setBusy(false)}}
const fields=(s?:Service)=><><div className="field-grid"><label>{t('Szolgáltatás neve','Service name')}<input name="hu" defaultValue={s?.hu} required maxLength={200}/></label><label>{t('Angol név (nem kötelező)','English name (optional)')}<input name="en" defaultValue={s?.en===s?.hu?'':s?.en} maxLength={200}/></label><label>{t('Magyar leírás','Hungarian description')}<textarea name="descriptionHu" defaultValue={s?.description[0]} maxLength={1000}/></label><label>{t('Angol leírás (nem kötelező)','English description (optional)')}<textarea name="descriptionEn" defaultValue={s?.description[1]===s?.description[0]?'':s?.description[1]} maxLength={1000}/></label><label>{t('Ár (Ft)','Price (HUF)')}<input name="price" type="number" min={0} max={10000000} step={1} defaultValue={s?.price} required/></label><label>{t('Időtartam','Duration')}<select name="minutes" defaultValue={s?.minutes||''} required><option value="">{t('Válassz időtartamot','Choose a duration')}</option>{Array.from({length:16},(_,i)=>(i+1)*30).map(m=><option key={m} value={m}>{m} {t('perc','minutes')}</option>)}</select></label></div><label>{t('Sorrend','Display order')}<input name="position" type="number" defaultValue={s?.position??services.length} required/></label><label className="check-label"><input type="checkbox" name="active" defaultChecked={s?!!s.active:true}/>{t('Látható és foglalható','Visible and bookable')}</label><button className="button" disabled={busy}>{t('Mentés','Save')}</button></>;
function resetTranslation(e:React.FormEvent<HTMLFormElement>){const input=e.target as HTMLInputElement;const target=input.name==='hu'?'en':input.name==='descriptionHu'?'descriptionEn':null;if(target)(e.currentTarget.elements.namedItem(target) as HTMLInputElement).value=''}
return <section><h2>{t('Szolgáltatások és árak','Services & prices')}</h2><p>{t('Itt módosíthatod a kezelések árát és időtartamát. A foglalható időpontokat a rendszer ezek alapján számolja, a munkaidő és a meglévő foglalások figyelembevételével.','Manage treatment prices and durations here. Available appointments are calculated from these durations, working hours and existing bookings.')}</p><TranslationNote en={en}/>{(failed||error)&&<p className="error" role="alert">{t('A művelet nem sikerült. Próbáld újra.','The request failed. Please try again.')}</p>}{saved&&<p className="saved-message" role="status">{t('Elmentve.','Saved.')}</p>}{!ready?<p>{t('Betöltés…','Loading…')}</p>:<><h3>{t('Új szolgáltatás','Add a service')}</h3><form className="editor-form faq-editor" onChange={resetTranslation} onSubmit={e=>save(e)}>{fields()}</form>{services.map(s=><details className="faq-edit-item" key={JSON.stringify(s)}><summary>{en?s.en:s.hu} · {money(s.price)} · {s.minutes} {t('perc','minutes')} {!s.active&&' · '+t('Rejtett','Hidden')}</summary><form className="editor-form faq-editor" onChange={resetTranslation} onSubmit={e=>save(e,s)}>{fields(s)}</form></details>)}</>}</section>}
