'use client';
import {useEffect,useState} from 'react';
import {categories,type Photo} from '@/lib/content';
export default function GalleryEditor({en}:{en:boolean}){const t=(a:string,b:string)=>en?b:a;const [photos,setPhotos]=useState<Photo[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
async function load(){setLoading(true);try{const r=await fetch('/api/gallery?admin=1');if(!r.ok)throw Error();setPhotos((await r.json() as {photos:Photo[]}).photos)}catch{setError('load')}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const file=data.get('photo') as File;setBusy(true);setError('');setMessage('');try{if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('format');return}const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>50000000){bitmap.close();setError('format');return}const canvas=document.createElement('canvas');const scale=Math.min(1,4000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext('2d');if(!context)throw Error();context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const clean=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error()),'image/jpeg',.94));data.set('photo',clean,'work.jpg');const r=await fetch('/api/gallery',{method:'POST',body:data});if(!r.ok)throw Error();form.reset();setMessage('uploaded');await load()}catch{setError('save')}finally{setBusy(false)}}
async function save(e:React.FormEvent<HTMLFormElement>,p:Photo){e.preventDefault();setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/gallery',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,service:f.get('service'),caption_hu:f.get('caption_hu'),caption_en:f.get('caption_en'),published:f.get('published')==='on'?1:0})});if(!r.ok)throw Error();setMessage('saved');await load()}catch{setError('save')}finally{setBusy(false)}}
const fields=(p?:Photo)=><><label>{t('Kezelés típusa','Treatment category')}<select name="service" defaultValue={p?.service||'hair'}>{categories.map(c=><option key={c.id} value={c.id}>{en?c.en:c.hu}</option>)}</select></label><label>{t('Magyar képaláírás','Hungarian caption')}<input name="caption_hu" required maxLength={300} defaultValue={p?.caption_hu}/></label><label>{t('Angol képaláírás','English caption')}<input name="caption_en" required maxLength={300} defaultValue={p?.caption_en}/></label></>;
return <section><h2>{t('Galéria kezelése','Manage your gallery')}</h2><p>{t('Tölts fel saját munkákat, és rendeld őket a megfelelő kezeléshez. Csak olyan fotót használj, amelynek közzétételéhez a vendég hozzájárult.','Upload your work and choose its treatment category. Only publish client photos with their permission.')}</p><form className="editor-form upload-form" onSubmit={upload}><label>{t('Új fotó','New photo')}<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required/><small>JPG, PNG, WebP · max. 10 MB</small></label>{fields()}<button className="button" disabled={busy}>{busy?t('Mentés…','Saving…'):t('Fotó feltöltése','Upload photo')}</button></form>{error&&<p role="alert" className="error">{error==='format'?t('Legfeljebb 10 MB-os JPG, PNG vagy WebP képet válassz.','Choose a JPG, PNG or WebP image up to 10 MB.'):t('A művelet nem sikerült. Próbáld újra.','The request failed. Please try again.')} <button onClick={load} className="text-link">{t('Frissítés','Refresh')}</button></p>}{message&&<p role="status" className="saved-message">{t('Sikeresen elmentve.','Saved successfully.')}</p>}{loading?<p>{t('Betöltés…','Loading…')}</p>:!photos.length?<div className="empty">{t('Még nincs feltöltött fotó. Az első feltöltés után megjelenik a weboldal galériájában.','No photos yet. Your first upload will appear in the website gallery.')}</div>:<div className="admin-photo-grid">{photos.map(p=><article key={p.id}><img src={'/api/photos/'+p.id} alt={en?p.caption_en:p.caption_hu}/><form className="editor-form" onSubmit={e=>save(e,p)}>{fields(p)}<label className="check-label"><input type="checkbox" name="published" defaultChecked={!!p.published}/>{t('Látható a galériában','Visible in the gallery')}</label><button className="button" disabled={busy}>{t('Módosítások mentése','Save changes')}</button></form></article>)}</div>}</section>}
