'use client';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Images,CalendarDays,MessageCircle,Settings,LogOut,ExternalLink} from 'lucide-react';
import Reservations from './reservations';
import GalleryEditor from './gallery-editor';
import FaqEditor from './faq-editor';
export default function Admin(){const [en,setEn]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);const t=(a:string,b:string)=>en?b:a;
async function logout(){try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw Error();window.location.assign('/admin')}catch{setError('connection')}}
async function password(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);if(f.get('newPassword')!==f.get('confirm')){setError('match');setBusy(false);return}try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'password',password:f.get('password'),newPassword:f.get('newPassword')})});if(!r.ok){const b=await r.json() as {error:string};setError(b.error);return}setSaved(true);window.location.assign('/admin')}catch{setError('connection')}finally{setBusy(false)}}
return <main className="admin-panel admin-shell"><header className="admin-top"><a className="brand" href="/"><span>IVETT KOVACS</span><small>STUDIO MANAGER</small></a><div><button className="language" onClick={()=>setEn(!en)}>HU / EN</button><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={16}/>{t('Weboldal','View site')}</a><button onClick={logout}><LogOut size={16}/>{t('Kilépés','Sign out')}</button></div></header><div className="admin-welcome"><p className="eyebrow">{t('A SZALONOD, EGY HELYEN','YOUR STUDIO, IN ONE PLACE')}</p><h1>{t('Üdv, Ivett.','Welcome, Ivett.')}</h1><p>{t('Foglalások, munkák és válaszok — alakítsd a weboldalt a saját ritmusodhoz.','Appointments, work and answers — keep your website up to date.')}</p></div>{error&&<p role="alert" className="error">{error==='match'?t('A jelszavak nem egyeznek.','Passwords do not match.'):error==='credentials'?t('A jelenlegi jelszó hibás.','The current password is incorrect.'):t('A művelet nem sikerült. Próbáld újra.','The request failed. Please try again.')}</p>}<Tabs defaultValue="bookings"><TabsList className="admin-tabs"><TabsTrigger value="bookings"><CalendarDays size={17}/>{t('Foglalások','Bookings')}</TabsTrigger><TabsTrigger value="gallery"><Images size={17}/>{t('Galéria','Gallery')}</TabsTrigger><TabsTrigger value="faq"><MessageCircle size={17}/>{t('Gyakori kérdések','FAQs')}</TabsTrigger><TabsTrigger value="settings"><Settings size={17}/>{t('Beállítások','Settings')}</TabsTrigger></TabsList><TabsContent value="bookings"><Reservations en={en}/></TabsContent><TabsContent value="gallery"><GalleryEditor en={en}/></TabsContent><TabsContent value="faq"><FaqEditor en={en}/></TabsContent><TabsContent value="settings"><h2>{t('Jelszó módosítása','Change password')}</h2><p>{t('A mentés után minden admin munkamenet megszűnik. Jelentkezz be az új jelszóval.','Saving signs out every admin session. Sign in again with your new password.')}</p><form className="editor-form password-form" onSubmit={password}><label>{t('Jelenlegi jelszó','Current password')}<input type="password" name="password" autoComplete="current-password" required maxLength={128}/></label><label>{t('Új jelszó (legalább 12 karakter)','New password (at least 12 characters)')}<input type="password" name="newPassword" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>{t('Új jelszó ismét','Confirm new password')}<input type="password" name="confirm" autoComplete="new-password" minLength={12} maxLength={128} required/></label><button className="button" disabled={busy}>{t('Új jelszó mentése','Save new password')}</button>{saved&&<p>{t('Jelszó elmentve.','Password saved.')}</p>}</form></TabsContent></Tabs></main>}
