import {account,adminSession,createSession,cookie,SESSION_COOKIE} from '@/lib/auth';
import {hashPassword,verifyPassword,digest} from '@/lib/password';
import {db,sameOrigin} from '@/lib/server';
import {cookies} from 'next/headers';
export async function POST(req:Request){if(!sameOrigin(req))return Response.json({error:'forbidden'},{status:403});try{const b=await req.json() as {action:string,username:string,password:string,newPassword:string};if(b.action==='logout'){const token=(await cookies()).get(SESSION_COOKIE)?.value;if(token)await db().prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await digest(token)).run();return Response.json({ok:true},{headers:{'Set-Cookie':cookie('',req,true)}})}
 if(b.action==='password'){const session=await adminSession();if(!session)return Response.json({error:'unauthorized'},{status:401});if(typeof b.newPassword!=='string'||b.newPassword.length<12||b.newPassword.length>128||b.newPassword===b.password)return Response.json({error:'password_length'},{status:400});if(typeof b.password!=='string'||!await verifyPassword(b.password,session.password_hash))return Response.json({error:'credentials'},{status:401});const hash=await hashPassword(b.newPassword);await db().batch([db().prepare('UPDATE admin_account SET password_hash=?,must_change=0,version=version+1,failures=0,locked_until=0 WHERE username=? AND version=?').bind(hash,session.username,session.version),db().prepare('DELETE FROM admin_sessions WHERE username=?').bind(session.username)]);return Response.json({ok:true},{headers:{'Set-Cookie':cookie('',req,true)}})}
 if(b.action!=='login'||typeof b.username!=='string'||typeof b.password!=='string'||b.password.length>128)return Response.json({error:'invalid'},{status:400});const a=await account();if(!a)return Response.json({error:'unavailable'},{status:503});if(a.locked_until>Date.now())return Response.json({error:'locked'},{status:429});
 // Count attempts atomically before password checking, including concurrent requests.
 const attempt=await db().prepare('UPDATE admin_account SET failures=CASE WHEN locked_until>0 THEN 1 ELSE failures+1 END,locked_until=CASE WHEN locked_until>0 THEN 0 WHEN failures>=4 THEN ? ELSE 0 END WHERE username=? AND locked_until<=? RETURNING failures').bind(Date.now()+15*60*1000,a.username,Date.now()).first<{failures:number}>();if(!attempt)return Response.json({error:'locked'},{status:429});
 if(b.username!==a.username||!await verifyPassword(b.password,a.password_hash))return Response.json({error:'credentials'},{status:401});await db().prepare('UPDATE admin_account SET failures=0,locked_until=0 WHERE username=?').bind(a.username).run();const token=await createSession(a);return Response.json({ok:true,mustChange:!!a.must_change},{headers:{'Set-Cookie':cookie(token,req),'Cache-Control':'no-store'}});
 }catch(e){console.error('Admin auth unavailable',e);return Response.json({error:'unavailable'},{status:503})}}
