'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Day={date:string,slots:number[],duration:number,busy:{start:number,end:number}[]};
const time=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Budapest'}).format(new Date());
export default function PublicCalendar({en,open,onOpenChange,services,onBook}:{en:boolean,open:boolean,onOpenChange:(v:boolean)=>void,services:{id:string,hu:string,en:string,minutes:number|null}[],onBook:(service:string,date:string,start:number)=>void}){
 const t=(a:string,b:string)=>en?b:a;const [service,setService]=useState(''),[date,setDate]=useState(today),[days,setDays]=useState<Day[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(false),[refresh,setRefresh]=useState(0);
 const selected=services.some(s=>s.id===service)?service:services[0]?.id||'';
 useEffect(()=>{if(!open||!selected)return;const controller=new AbortController();setLoading(true);setError(false);setDays([]);fetch('/api/calendar?'+new URLSearchParams({date,service:selected}),{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();setDays((await r.json() as {days:Day[]}).days)}).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[open,date,selected,refresh]);
 const minTime=Math.min(540,...days.flatMap(d=>[...d.slots,...d.busy.filter(b=>b.start!==0||b.end!==1440).map(b=>b.start)])),maxTime=Math.max(1020,...days.flatMap(d=>[...d.slots.map(n=>n+30),...d.busy.filter(b=>b.start!==0||b.end!==1440).map(b=>b.end)]));
 function move(n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);setDate(d.toISOString().slice(0,10)<today()?today():d.toISOString().slice(0,10))}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="public-calendar-dialog"><DialogTitle>{t('Szabad időpontok','Find an appointment')}</DialogTitle><DialogDescription>{t('Válassz kezelést, majd kattints egy szabad kezdési időpontra. Az időpontok Budapest időzónája szerint jelennek meg.','Choose a treatment, then click an available start time. All times are in the Budapest time zone.')}</DialogDescription><div className="public-calendar-controls"><label>{t('Kezelés','Treatment')}<select value={selected} onChange={e=>setService(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{en?s.en:s.hu} · {s.minutes} {t('perc','min')}</option>)}</select></label><label>{t('Kezdőnap','Starting date')}<input type="date" value={date} min={today()} max={new Date(Date.now()+358*864e5).toISOString().slice(0,10)} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label><button type="button" className="text-link" disabled={date<=today()} onClick={()=>move(-7)}>{t('Előző hét','Previous week')}</button><button type="button" className="text-link" disabled={date>=new Date(Date.now()+351*864e5).toISOString().slice(0,10)} onClick={()=>move(7)}>{t('Következő hét','Next week')}</button></div><p className="calendar-key">{t('Szabad kezdési időpont · Szürke: nem elérhető','Available start time · Grey: unavailable')}</p>{loading?<p role="status">{t('Betöltés…','Loading…')}</p>:error?<p role="alert">{t('Nem sikerült betölteni.','Unable to load.')} <button onClick={()=>setRefresh(x=>x+1)}>{t('Újra','Retry')}</button></p>:<div className="public-calendar-week">{days.map(day=><section key={day.date}><h3>{new Intl.DateTimeFormat(en?'en-GB':'hu-HU',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(day.date+'T12:00:00Z'))}</h3><div className="public-day-blocks" style={{height:(maxTime-minTime)/30*48}}>{[...day.slots.map(start=>({start,end:start+day.duration,free:true})),...day.busy.map(b=>({...b,free:false}))].sort((a,b)=>a.start-b.start).map((block,i)=>block.free?<button className="public-slot" style={{top:(block.start-minTime)/30*48,height:46}} title={time(block.start)+'–'+time(block.end)} key={'s'+i} onClick={()=>onBook(selected,day.date,block.start)}><strong>{time(block.start)}</strong><small>{t('Vége','Until')} {time(block.end)}</small></button>:<div className="public-busy" style={{top:(Math.max(minTime,block.start)-minTime)/30*48,height:(Math.min(maxTime,block.end)-Math.max(minTime,block.start))/30*48-2}} key={'b'+i}><span>{block.start===0&&block.end===1440?t('Egész nap','All day'):time(block.start)+'–'+time(block.end)}</span><small>{t('Nem elérhető','Unavailable')}</small></div>)}{!day.slots.length&&!day.busy.length&&<p className="no-slots">{t('Nincs szabad időpont','No available appointments')}</p>}</div></section>)}</div>}</DialogContent></Dialog>
}
