'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,Expand,ImageOff,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {defaultFaqs,type Photo,type Faq} from '@/lib/content';
import {useCatalog} from '@/hooks/use-catalog';
import {portfolio} from '@/lib/portfolio';
import {staticSite,assetUrl} from '@/lib/site-mode';
import {instagramUrl} from '@/lib/catalog';
export default function Showcase({en}:{en:boolean}){const {services:categories,contact}=useCatalog();const t=(a:string,b:string)=>en?b:a;const [photos,setPhotos]=useState<Photo[]>([]),[faqs,setFaqs]=useState<Faq[]>([]),[filter,setFilter]=useState('all'),[active,setActive]=useState<string|null>(null),[state,setState]=useState('loading');
async function load(){if(staticSite){setPhotos(portfolio);setFaqs(defaultFaqs);setState('ready');return}setState('loading');try{const [g,f]=await Promise.all([fetch('/api/gallery'),fetch('/api/faq')]);if(!g.ok||!f.ok)throw Error();setPhotos((await g.json() as {photos:Photo[]}).photos);setFaqs((await f.json() as {faqs:Faq[]}).faqs);setState('ready')}catch{setState('error')}}useEffect(()=>{load()},[]);
const shown=photos.filter(p=>filter==='all'||p.service===filter),index=shown.findIndex(p=>p.id===active),photo=shown[index];const category=(id:string)=>categories.find(c=>c.id===id)?.[en?'en':'hu'];const caption=(p:Photo)=>(en?p.caption_en:p.caption_hu)||category(p.service)||t('Sminktetoválás','Permanent makeup');const photoUrl=(p:Photo)=>assetUrl(staticSite?portfolio.find(x=>x.id===p.id)!.src:'/api/photos/'+p.id);function move(n:number){setActive(shown[(index+n+shown.length)%shown.length].id)}
return <><section id="munkak" className="section work"><p className="eyebrow">03 / {t('MUNKÁIM','MY WORK')}</p><div className="section-heading"><h2>{t('A részletek','Let the details')}<br/><em>{t('magukért beszélnek.','speak.')}</em></h2><p>{t('Szemöldök- és ajaktetoválások, közelről. Kattints egy fotóra a részletekért.','Brow and lip treatments, up close. Open a photo to explore the details.')}</p></div><div className="gallery-filters" role="group" aria-label={t('Szűrés kezelés szerint','Filter by treatment')}>{[{id:'all',hu:'Összes munka',en:'All work'},...categories.filter(c=>photos.some(p=>p.service===c.id))].map(c=><button key={c.id} aria-pressed={filter===c.id} className={filter===c.id?'active':''} onClick={()=>{setFilter(c.id);setActive(null)}}>{en?c.en:c.hu}</button>)}</div>{state==='loading'?<p role="status">{t('Fotók betöltése…','Loading photos…')}</p>:state==='error'?<div className="gallery-empty"><ImageOff/><p>{t('A galéria most nem tölthető be.','The gallery could not be loaded.')}</p><button className="text-link" onClick={load}>{t('Újrapróbálás','Try again')}</button></div>:shown.length?<div className="gallery-grid" key={filter}>{shown.map(p=><button className="gallery-card" key={p.id} onClick={()=>setActive(p.id)} aria-label={t('Fotó megnyitása: ','Open photo: ')+(caption(p))}><div><img src={photoUrl(p)} alt={caption(p)} loading="lazy"/><span><Expand size={19}/></span></div><small>{category(p.service)}</small><h3>{caption(p)}</h3></button>)}</div>:<div className="gallery-empty"><Camera size={28}/><p>{t('A galéria hamarosan új munkákkal bővül.','New work will be added to the gallery soon.')}</p><a href={instagramUrl(contact.instagram)} target="_blank" rel="noreferrer" className="text-link">{t('Addig nézz körül az Instagramon','Explore my work on Instagram')}</a></div>}</section>
<section id="gyik" className="section faq-section"><div><p className="eyebrow">04 / {t('GYAKORI KÉRDÉSEK','FAQ')}</p><h2>{t('Amit jó','Good to')}<br/><em>{t('tudni.','know.')}</em></h2><p>{t('Nem találod a választ? Keress bátran, szívesen segítek.','Have another question? Get in touch — I’m happy to help.')}</p><a className="text-link" href="#kapcsolat">{t('Kapcsolatfelvétel','Get in touch')}</a></div><Accordion type="single" collapsible className="faq-list">{faqs.map(f=><AccordionItem key={f.id} value={f.id}><AccordionTrigger>{en?(f.question_en||f.question_hu):f.question_hu}</AccordionTrigger><AccordionContent>{en?(f.answer_en||f.answer_hu):f.answer_hu}</AccordionContent></AccordionItem>)}</Accordion></section>
<Dialog open={!!photo} onOpenChange={o=>{if(!o)setActive(null)}}><DialogContent className="gallery-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}}>{photo&&<><DialogTitle>{caption(photo)}</DialogTitle><DialogDescription>{category(photo.service)} · {index+1} / {shown.length}</DialogDescription><div className="full-photo"><img key={photo.id} src={photoUrl(photo)} alt={caption(photo)}/></div><div className="lightbox-actions"><button disabled={shown.length<2} onClick={()=>move(-1)} aria-label={t('Előző fotó','Previous photo')}><ChevronLeft/>{t('Előző','Previous')}</button><a href={photoUrl(photo)} target="_blank" rel="noreferrer">{t('Eredeti méret','Original size')}</a><button disabled={shown.length<2} onClick={()=>move(1)} aria-label={t('Következő fotó','Next photo')}>{t('Következő','Next')}<ChevronRight/></button></div></>}</DialogContent></Dialog></>}
