export const categories=[{id:'hair',hu:'Szálas szemöldök',en:'Hairstroke brows'},{id:'powder',hu:'Púderes szemöldök',en:'Powder brows'},{id:'lips',hu:'Ajaktetoválás',en:'Lip blush'}];
export type Photo={id:string,service:string,caption_hu:string,caption_en:string,published:number};
export type Faq={id:string,question_hu:string,question_en:string,answer_hu:string,answer_en:string,position:number,published:number};
export const defaultFaqs:Faq[]=[
{id:'consultation',question_hu:'Kérhetek konzultációt a kezelés előtt?',question_en:'Can I book a consultation first?',answer_hu:'Igen. Az előzetes konzultáció felrajzolást és tervezést tartalmaz, díja 10 000 Ft. Kezelés foglalásakor ezt levonjuk a kezelés árából.',answer_en:'Yes. The design consultation includes mapping and planning and costs HUF 10,000. This fee is deducted from the treatment price when you book.',position:0,published:1},
{id:'touchup',question_hu:'Az ár tartalmazza a korrekciót?',question_en:'Is a touch-up included in the price?',answer_hu:'A sminktetoválás ára 12 héten belüli korrekciót tartalmaz. Szükség esetén a második korrekció díja 12 héten belül 25 000 Ft.',answer_en:'PMU prices include a touch-up within 12 weeks. If needed, a second touch-up within 12 weeks costs HUF 25,000.',position:1,published:1},
{id:'previous',question_hu:'Van már sminktetoválásom. Így is foglalhatok?',question_en:'Can I book if I already have permanent makeup?',answer_hu:'A foglalási űrlapon jelezd a korábbi kezelést. Az időpont véglegesítése előtt egyeztetünk a meglévő tetoválásról és a lehetőségekről.',answer_en:'Please mention your previous treatment in the booking form. Before confirming the appointment, we will discuss your existing makeup and the available options.',position:2,published:1},
{id:'confirmation',question_hu:'Mikor válik véglegessé a foglalásom?',question_en:'When is my booking confirmed?',answer_hu:'Az űrlap elküldésével időpontkérést rögzítesz. Ivett a megadott elérhetőségen egyeztet veled, és visszaigazolja a foglalást.',answer_en:'Submitting the form creates an appointment request. Ivett will contact you using the details provided and confirm your booking.',position:3,published:1},
{id:'change',question_hu:'Hogyan módosíthatom vagy mondhatom le az időpontomat?',question_en:'How can I change or cancel my appointment?',answer_hu:'Kérlek, jelezd minél előbb telefonon a +36 30 892 1392 számon vagy az ivettkovacs5@gmail.com email-címen.',answer_en:'Please contact me as soon as possible at +36 30 892 1392 or ivettkovacs5@gmail.com.',position:4,published:1},
];
