import {reservationEmail} from './reservation-email';
import {env} from 'cloudflare:workers';
import {db} from '@/lib/server';
import {getContact,getServices} from '@/lib/catalog-server';
export type Reservation={id:string,service:string,date:string,start:number,end:number,name:string,email:string,status:string,language:string,service_name:string,booked_price:number|null,status_event:string};
type Outbox={id:string,booking_id:string,kind:string,payload:string,state:string,first_attempt:number|null};
export function emailConfigured(){const e=env as unknown as {RESEND_API_KEY?:string,RESEND_FROM?:string};return !!e.RESEND_API_KEY&&!!e.RESEND_FROM;}
export async function notificationPayload(b:Reservation,kind:string){
 const [contact,services]=await Promise.all([getContact(),getServices()]);
 const service=services.find(s=>s.id===b.service);
 const name=b.language==='en'?(service?.en||b.service_name||service?.hu||b.service):(b.service_name||service?.hu||b.service);
 return {to:[b.email],reply_to:contact.email,...reservationEmail({id:b.id,name:b.name,date:b.date,start:b.start,end:b.end,price:b.booked_price,service:name,language:b.language},kind,contact)};
}
export async function sendNotification(id:string){if(!emailConfigured())return 'not_configured';const now=Date.now();let job=await db().prepare('SELECT * FROM email_outbox WHERE id=?').bind(id).first<Outbox>();if(!job)return 'missing';if(['accepted','superseded','manual_review'].includes(job.state))return job.state;
const current=await db().prepare('SELECT status,status_event FROM bookings WHERE id=?').bind(job.booking_id).first<{status:string,status_event:string}>();if(!current||current.status_event!==id||current.status!==job.kind){await db().prepare("UPDATE email_outbox SET state='superseded' WHERE id=? AND state!='accepted'").bind(id).run();return 'superseded'}
if(job.first_attempt&&now-job.first_attempt>23*60*60*1000){await db().prepare("UPDATE email_outbox SET state='manual_review',error='Delivery outcome must be checked with the provider before retrying.' WHERE id=? AND state!='accepted'").bind(id).run();return 'manual_review'}
const claim=await db().prepare("UPDATE email_outbox SET state='sending',locked_until=? WHERE id=? AND state IN ('queued','failed','sending') AND locked_until<=? AND EXISTS (SELECT 1 FROM bookings WHERE bookings.id=email_outbox.booking_id AND bookings.status_event=email_outbox.id AND bookings.status=email_outbox.kind) RETURNING id").bind(now+120000,id,now).first();if(!claim)return 'sending';
try{const e=env as unknown as {RESEND_API_KEY:string,RESEND_FROM:string};let payload=JSON.parse(job.payload);if(!payload.from){payload={...payload,from:e.RESEND_FROM};await db().prepare('UPDATE email_outbox SET payload=? WHERE id=?').bind(JSON.stringify(payload),id).run();}await db().prepare('UPDATE email_outbox SET first_attempt=COALESCE(first_attempt,?) WHERE id=?').bind(now,id).run();const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':`Bearer ${e.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`booking-${id}`},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(`provider_http_${response.status}`);const result=await response.json() as {id?:string};if(!result.id)throw Error('provider_response');await db().prepare("UPDATE email_outbox SET state='accepted',provider_id=?,locked_until=0,error=NULL WHERE id=?").bind(result.id,id).run();return 'accepted';}catch(e){await db().prepare("UPDATE email_outbox SET state='failed',locked_until=0,error=? WHERE id=?").bind(e instanceof Error?e.message:'send_failed',id).run();return 'failed';}}
